[package]
name = "math_machines"
version = "0.1.0"
edition = "2021"

[lib]
name       = "math_machines"
path       = "src/lib.rs"
doc        = true
crate-type = ["lib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
